### ISSUE TITLE
Combining Date Ranges

### ISSUE THREAD

**Issue by DannyLee89** [DannyLee89/DateRangeProvider#1]
There are a few scenarios that can happen when combining Date Ranges as I see it.

1. Range 1 and Range 2 butt up against each other. That is, the `EndDate` of range 1 and the `StartDate` of range 2 are equal.
2. Range 1 and Range 2 overlap to some degree.
3. Rane 1 and Range 2 don't meet and don't overlap.

What are some possibilities of behaviors for these scenarios?

**Comment by SteveTeece** [comment]
Hi Danny,

I'm having trouble understanding why you would want to combine date ranges.  Can you give us a Use Case or two to better illustrate your vision?

I'd love to help with this project.  I've been meaning to do something similar myself for a while, and never got to it.

**Comment by DannyLee89** [comment]
Awesome! I'd appreciate it!

That's a good question. I thought the option to do so might be useful to someone, but didn't really have a use case in mind. Maybe it could be useful for some payroll functions when figuring days in pay periods? Maybe it isn't too useful in the end.

If there are other use cases you think this library could serve, I'd love to try and get them incorporated!

**Comment by DannyLee89** [comment]
@SteveTeece, Thinking more about this, I'm wondering if methods on a collection of date ranges might be more beneficial than combining them.  Keeping the payroll use case in mind, it might be useful to perform operations on a handful of ranges.  I'm going to close this issue for now, and if it deems useful later we can re-evaluate.
